### ISSUE TITLE
java.lang.NullPointerException 	at com.crawljax.core.state.InMemoryStateFlowGraph.getShortestPath(InMemoryStateFlowGraph.java:267) in version 4.1. 

### ISSUE THREAD

**Issue by maria456123** [crawljax/crawljax#526] opened 2021-09-05 17:00 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yrahulkr** [comment] 2021-09-13 11:20
Is it an uncaught exception? Does Crawljax continue after error or does it stop?

**Comment by maria456123** [comment] 2021-09-15 13:18
The browser window popped up and then the crawljax stopped with this
exception.

**Comment by amesbah** [comment] 2023-02-17 19:47
Cannot reproduce. Closing for now.

**Closed by amesbah** 2023-02-17 19:47 UTC
